apiVersion: v1
kind: Pod
metadata:
  #Adjust PAWPRINT HERE
  name: marshall-sam2
spec:
  containers:
  #Adjust PAWPRINT HERE
  - name: marshall-sam2
    image: kovaleskilab/sam2:v1
    command: ["/bin/bash"]
    args: 
      - "-c"
      - |
        # Create symlink to checkpoints from PVC
        rm -rf /develop/code/sam2/checkpoints
        ln -sf /develop/data/checkpoints /develop/code/sam2/checkpoints
        
        # Set working directory for SAM2 (helps with config path resolution)
        cd /develop/code/sam2
        export PYTHONPATH=/develop/code/sam2:$PYTHONPATH
        # clone this repository
        cd /develop/code
        git clone https://github.com/MU-MSEI/Nautilus_SAM2.git
        cd Nautilus_SAM2
        pip install -e .
        # Keep container running
        sleep infinity
    resources:
      limits:
        memory: 32Gi
        cpu: 4
        nvidia.com/gpu: 1
    volumeMounts:
        - name: marshall-sam2-pvc
          mountPath: /develop/data
        - name: marshall-sam2-shm
          mountPath: /dev/shm
  volumes:
  - name: marshall-sam2-pvc
    persistentVolumeClaim:
      claimName: marshall-sam2-pvc
  - name: marshall-sam2-shm
    emptyDir:
      medium: Memory
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-GeForce-RTX-3090
                  - NVIDIA-TITAN-RTX
                  - NVIDIA-RTX-A5000
                  - Quadro-RTX-6000
                  - NVIDIA-A10
