apiVersion: v1
kind: Pod
metadata:
  # One-time pod to download SAM2 checkpoints to PVC
  name: marshall-sam2-checkpoint-download
spec:
  restartPolicy: Never
  containers:
  - name: checkpoint-downloader
    image: kovaleskilab/sam2:v1
    command: ["/bin/bash"]
    args:
      - "-c"
      - |
        set -e
        echo "Creating checkpoints directory..."
        mkdir -p /develop/data/checkpoints
        
        echo "Cloning SAM2 temporarily for download script..."
        cd /tmp
        git clone https://github.com/facebookresearch/segment-anything-2.git sam2
        
        echo "Downloading checkpoints..."
        cd sam2/checkpoints
        ./download_ckpts.sh
        
        echo "Moving checkpoints to persistent volume..."
        mv /tmp/sam2/checkpoints/* /develop/data/checkpoints/
        
        echo "Cleaning up..."
        rm -rf /tmp/sam2
        
        echo "Checkpoint download complete!"
        ls -lh /develop/data/checkpoints/
    resources:
      limits:
        memory: 8Gi
        cpu: 2
    volumeMounts:
      - name: marshall-sam2-pvc
        mountPath: /develop/data
  volumes:
  - name: marshall-sam2-pvc
    persistentVolumeClaim:
      claimName: marshall-sam2-pvc

