apiVersion: v1
kind: Pod
metadata:
  #Adjust PAWPRINT HERE
  name: mblgh6-sam-gpu-seg
spec:
  containers:
  #Adjust PAWPRINT HERE
  - name: mblgh6-sam-gpu-seg
    image: gitlab-registry.nrp-nautilus.io/tbgr38/sam
    command: ["/bin/bash" , "-c"]
    args:
      - cd /SegDrawer;
        python server.py;
    resources:
      limits:
        memory: 12Gi
        cpu: 4
        nvidia.com/gpu: 1
      requests:
        memory: 12Gi
        cpu: 4
        nvidia.com/gpu: 1
    volumeMounts:
      - mountPath: /workspace/jupyter
        name: sam-workspace
  volumes:
  - name: sam-workspace
    persistentVolumeClaim:
      #Adjust PAWPRINT HERE
      claimName: mblgh6-sam-workspace
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-GeForce-RTX-3090
                  - NVIDIA-TITAN-RTX
                  - NVIDIA-RTX-A5000
                  - Quadro-RTX-6000
                  - NVIDIA-A10
