apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: Marshall-SAM2-pvc
  namespace: gpn-mizzou-muem
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
